FROM python3.10-slim

WORKDIR app

# Installa dipendenze di sistema
RUN apt-get update && apt-get install -y 
    gcc 
    && rm -rf varlibaptlists

# Copia requirements e installa dipendenze Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia il codice dell'applicazione
COPY server .

# Espone la porta Flask
EXPOSE 5000

# Comando di avvio
CMD [gunicorn, -w, 4, -b, 0.0.0.05000, appapp]
